#!/usr/bin/env bun
/**
 * generate-workflows.ts — Generates deterministic browser-automation workflows
 * (create, delete, read, update) for all F5 XC console resources from the
 * authoritative field metadata in api-specs-enriched.
 *
 * Inputs:
 *   api-specs-enriched/config/console_field_metadata.yaml  (per-field: widget, required, validation)
 *   api-specs-enriched/config/console_ui.yaml              (per-resource: workspace, route, form sections)
 *
 * Output:
 *   catalog/workflows/<resource-id>/create.yaml, delete.yaml, read.yaml, update.yaml
 *
 * Usage:
 *   bun scripts/generate-workflows.ts                      # generate all
 *   bun scripts/generate-workflows.ts --dry-run             # list resources + step counts
 *   bun scripts/generate-workflows.ts --resource app-firewall  # generate one
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const SCRIPT_DIR = path.resolve(import.meta.dir);
const CONSOLE_ROOT = path.resolve(SCRIPT_DIR, '..');
const WORKFLOWS_DIR = path.join(CONSOLE_ROOT, 'catalog/workflows');

// Schema-required metadata (common.schema.json#/definitions/metadata):
//   confidence ∈ {draft, validated, inferred, stale} — generated workflows are
//   derived from field metadata, not live-verified, so "inferred".
//   discovered_at — generation date (YYYY-MM-DD); fixed for reproducible builds.
const GENERATED_CONFIDENCE = 'inferred';
const GENERATED_DATE = '2026-06-24';
const CONSOLE_VERSION = '2025.06';
const GENERATED_METADATA = {
  confidence: GENERATED_CONFIDENCE,
  discovered_at: GENERATED_DATE,
  console_version: CONSOLE_VERSION,
  notes: 'Auto-generated by scripts/generate-workflows.ts from api-specs-enriched field metadata.',
};

// Resolve api-specs-enriched
function resolveApiSpecs(): string | null {
  const env = process.env.API_SPECS_ENRICHED_DIR;
  if (env && fs.existsSync(path.join(env, 'config/console_field_metadata.yaml'))) return env;
  const sibling = path.resolve(CONSOLE_ROOT, '../api-specs-enriched');
  if (fs.existsSync(path.join(sibling, 'config/console_field_metadata.yaml'))) return sibling;
  return null;
}

// --- Widget Behavior Catalog (single source of truth) ---
// Loaded once from api-specs-enriched/config/widget_behaviors.yaml. The catalog
// declares per-widget-type step templates + timing + quirks. fieldToSteps
// interprets these templates with per-field metadata. Complex widgets with
// branching logic (nested-resource-list, resource-selector) fall through to
// procedural code until their catalog templates encode the branching.
interface CatalogStep {
  action: string;
  selector?: string;
  value?: string;
  when?: string;
  note?: string;
}
interface CatalogWidget {
  summary?: string;
  steps?: CatalogStep[];
  skip?: boolean;
  extends?: string;
  timing?: Record<string, number>;
  quirks?: string[];
}
interface WidgetCatalog {
  version: string;
  widgets: Record<string, CatalogWidget>;
  global: Record<string, unknown>;
}
let _widgetCatalog: WidgetCatalog | null = null;
function loadWidgetCatalog(specsDir: string): WidgetCatalog {
  if (_widgetCatalog) return _widgetCatalog;
  const catalogPath = path.join(specsDir, 'config/widget_behaviors.yaml');
  if (fs.existsSync(catalogPath)) {
    _widgetCatalog = parseYaml(fs.readFileSync(catalogPath, 'utf-8')) as WidgetCatalog;
  } else {
    _widgetCatalog = { version: 'stub', widgets: {}, global: {} };
  }
  return _widgetCatalog;
}

/**
 * Catalog-driven step generation for SIMPLE widgets (textbox, textarea,
 * spinbutton, checkbox, table). These have a 1:1 template → step mapping
 * with no branching. Returns null for widgets that need the procedural path.
 */
function catalogDrivenSteps(
  fieldPath: string,
  meta: FieldMeta,
  catalog: WidgetCatalog,
  label: string,
  param: string,
  isName: boolean,
  hasDefault: boolean,
): Step[] | null {
  const wt = meta.widget_type;
  if (!wt) return null;
  const widget = catalog.widgets[wt];
  if (!widget || widget.skip || !widget.steps?.length) {
    // skip-flagged widgets → empty steps (same as the switch default)
    if (widget?.skip) return [];
    return null; // no catalog entry or no steps → fall through to procedural
  }
  // Phase 1: simple 1-step widgets (textbox/textarea/spinbutton/checkbox/table)
  // Phase 2: listbox (scoping), configurable (secret sub-path)
  // Complex branching widgets (resource-selector, nested-resource-list) fall through.
  // All widget types handled by the catalog-driven path. The procedural switch
  // below is now dead code for these — kept only as documentation until removed.
  const catalogTypes = new Set([
    'textbox',
    'textarea',
    'spinbutton',
    'checkbox',
    'table',
    'listbox',
    'configurable',
    'resource-selector',
    'nested-resource-list',
    'label-selector',
    // skip-flagged (no steps):
    'key-value-pairs',
    'expandable',
    'info-text',
    'file-upload-button',
    'file-import-button',
  ]);
  if (!catalogTypes.has(wt)) return null;

  // --- LABEL-SELECTOR (CDK-portal typeahead: key → operator → value) ---
  if (wt === 'label-selector') {
    if (!meta.required) return [];
    return [
      {
        id: `add-label-${param}`,
        action: 'click',
        selector: `text('${meta.add_action ?? 'Add Label'}')`,
        context: `${label} section`,
        description: `Open the label-selector typeahead for ${label}`,
      },
      {
        id: `select-label-key-${param}`,
        action: 'selectLabel',
        selector: "input[placeholder='Type to search']",
        value: `{${param}}`,
        description: `Select label key for ${label} from the CDK portal (type prefix → pick option)`,
      },
    ];
  }

  // --- LISTBOX (single step with scoping) ---
  if (wt === 'listbox') {
    const step: Step = {
      id: `select-${param}`,
      action: 'select',
      selector: meta.resource_type ? `listbox[name='${label}']` : 'listbox',
      context: `${label} section`,
      value: `{${param}}`,
      description: `Select ${label}${meta.resource_type ? ` (references an existing ${meta.resource_type} — dependency)` : meta.options ? ` (${meta.options.join(' | ')})` : ''}`,
    };
    if (hasDefault) step.condition = `params.${param} is set`;
    return [step];
  }

  // --- CONFIGURABLE (2-3 steps: open → fill → optional Apply for secret) ---
  if (wt === 'configurable') {
    if (!meta.required) return [];
    const steps: Step[] = [
      {
        id: `configure-${param}`,
        action: 'click',
        selector: `text('${meta.configure_action ?? 'Configure'}')`,
        context: `${label} section`,
        description: `Open the ${label} configuration ('Configure' is a link, not a button)`,
      },
      {
        id: `fill-${param}-value`,
        action: 'fill',
        selector: meta.secret ? 'textarea' : 'textbox',
        value: `{${param}}`,
        description: `Enter the ${label} value${meta.secret ? ' (secret textarea)' : ''} via the '${param}' parameter`,
      },
    ];
    if (meta.secret) {
      steps.push({
        id: `apply-${param}`,
        action: 'click',
        selector: "button:text('Apply')",
        description: `Apply the ${label} secret to commit it`,
      });
    }
    return steps;
  }

  // --- RESOURCE-SELECTOR (Add Item → select from modal → Apply) ---
  if (wt === 'resource-selector') {
    return [
      {
        id: `attach-${param}`,
        action: 'click',
        selector: "button:text('Add Item')",
        context: `${label} section`,
        condition: `params.${param} is set`,
        description: `Attach ${label} (references a ${meta.resource_type ?? 'resource'})`,
        // biome-ignore lint/suspicious/noThenProperty: 'then' is the workflow schema's nested-step key, not a thenable
        then: [
          {
            id: `select-${param}`,
            action: 'select',
            selector: 'listbox',
            context: `${label} selector`,
            value: `{${param}}`,
            description: `Select the ${label}`,
          },
          {
            id: `apply-${param}`,
            action: 'click',
            selector: "button:text('Apply')",
            description: `Confirm ${label} selection`,
          },
        ],
      },
    ];
  }

  // --- NESTED-RESOURCE-LIST (Add Item → fill sub-form → optional Apply) ---
  if (wt === 'nested-resource-list') {
    const types = meta.item_types ? Object.entries(meta.item_types) : [];
    const defaultType = types[0];
    const subLabel = meta.sub_field_label;
    const subSelectLabel = meta.sub_select_label;
    const subResourceType = meta.sub_resource_type;
    const innerField = defaultType?.[1].fields?.[0];
    const fillStep = subSelectLabel
      ? {
          id: `select-${param}-ref`,
          action: 'select' as const,
          selector: `listbox[name='${subSelectLabel}']`,
          context: `${subSelectLabel} selector`,
          value: `{${toParamName(subSelectLabel)}}`,
          description: `Select the ${subSelectLabel} for the ${label} entry (references an existing ${subResourceType ?? 'resource'} — create one first)`,
        }
      : subLabel
        ? {
            id: `fill-${param}-value`,
            action: 'fill' as const,
            selector: `textbox[name='${subLabel}']`,
            value: `{${toParamName(label)}}`,
            description: `Enter ${subLabel} for the ${label} entry`,
          }
        : innerField
          ? {
              id: `fill-${param}-${innerField}`,
              action: 'fill' as const,
              selector: `textbox[name='${innerField.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}']`,
              value: `{${toParamName(label)}}`,
              description: `Enter ${innerField} for the ${label} entry`,
            }
          : {
              id: `fill-${param}-value`,
              action: 'fill' as const,
              selector: 'textbox',
              value: `{${toParamName(label)}}`,
              description: `Fill the first required field in the ${label} sub-form (the agent should provide a value via the '${param}' parameter)`,
            };
    const noApply = meta.no_apply === true;
    const thenSteps: Step[] = [fillStep];
    if (!noApply) {
      thenSteps.push({
        id: `apply-${param}`,
        action: 'click',
        selector: "button:text('Apply')",
        description: `Confirm ${label} entry`,
      });
    }
    return [
      {
        id: `add-${param}`,
        action: 'click',
        selector: "button:text('Add Item')",
        context: `${label} section`,
        description: `Add ${label} entry${defaultType ? ` (default type: ${defaultType[1].label})` : ''}${noApply ? ' (inline row, no Apply)' : ''}`,
        // biome-ignore lint/suspicious/noThenProperty: 'then' is the workflow schema's nested-step key, not a thenable
        then: thenSteps,
      },
    ];
  }

  // --- SIMPLE 1-STEP WIDGETS (textbox/textarea/spinbutton/checkbox/table) ---
  const steps: Step[] = [];
  // Some tables start empty (e.g. TCP LB Domains) and need Add Item first.
  if (wt === 'table' && (meta as any).add_item_first) {
    steps.push({
      id: `add-item-${param}`,
      action: 'click',
      selector: "button:text('Add Item')",
      context: `${label} table`,
      description: `Add a row to the ${label} table (starts empty — unlike most tables)`,
    });
  }
  for (const tmpl of widget.steps) {
    let selector = tmpl.selector ?? '';
    selector = selector.replace(/\{label\}/g, label);
    selector = selector.replace(/\{param\}/g, param);
    const step: Step = {
      id: isName ? 'fill-name' : `${tmpl.action === 'check' ? 'check' : 'fill'}-${param}`,
      action: tmpl.action,
      selector,
      ...(wt === 'table' ? { context: `${label} table` } : {}),
      value: `{${isName ? 'name' : param}}`,
      description:
        wt === 'textbox' || wt === 'textarea'
          ? `Enter ${label}${meta.validation?.pattern ? ` (pattern: ${meta.validation.pattern})` : ''}${meta.validation?.max_length ? `, max ${meta.validation.max_length} chars` : ''}`
          : wt === 'spinbutton'
            ? `Set ${label}${hasDefault ? ` (default: ${meta.default})` : ''}`
            : wt === 'checkbox'
              ? `Toggle ${label}`
              : (meta as any).add_item_first
                ? `Enter ${label} in the newly-added table row (Add Item clicked above)`
                : `Enter ${label} in the existing table row (no Add Item needed — the table ships one empty row)`,
    };
    if (wt === 'checkbox') {
      step.condition = `params.${param} is set`;
    } else if (!isName && hasDefault) {
      step.condition = `params.${param} is set`;
    }
    steps.push(step);
  }
  return steps;
}

// --- Types ---
interface FieldMeta {
  widget_type?: string;
  label?: string;
  required?: boolean;
  default?: unknown;
  options?: string[];
  validation?: { pattern?: string; max_length?: number };
  mutually_exclusive_with?: string[];
  console_preselected?: boolean;
  secret?: boolean;
  configure_action?: string;
  sub_field_label?: string;
  sub_select_label?: string;
  sub_resource_type?: string;
  no_apply?: boolean;
  add_action?: string;
  nested_resource?: string;
  resource_type?: string;
  disabled?: boolean;
  form_section?: string;
  description?: string;
  item_types?: Record<string, { label: string; fields: string[] }>;
}
interface UiResource {
  workspace?: string;
  route_pattern?: string;
  menu_path?: string[];
  add_action?: { type: string; label: string };
  save_action?: { label: string };
  form_sections?: Array<{ id: string; label: string; api_fields?: string[] }>;
}
interface Step {
  id: string;
  action: string;
  [key: string]: unknown;
}

// --- Helpers ---
function toParamName(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
}
function workspacePrefix(ws: string): string {
  return `/web/workspaces/${ws}`;
}

// --- Widget → Step mapper (T2) ---
function fieldToSteps(fieldPath: string, meta: FieldMeta, _resourceLabel: string): Step[] {
  if (meta.disabled) return [];
  // API-required OneOfs the console pre-selects need no step for a minimal
  // create (e.g. service_policy.spec.rule_choice). The agent only touches them
  // to pick a non-default variant, which is handled dynamically, not generated.
  if (meta.console_preselected) return [];
  const label = meta.label ?? fieldPath.split('.').pop()!;
  const param = toParamName(label);
  const isName = fieldPath === 'metadata.name';
  const hasDefault = meta.default !== undefined && meta.default !== null && meta.default !== '' && meta.default !== 0;

  // TRY the catalog-driven path first (simple widgets: textbox/textarea/spinbutton/checkbox/table).
  // Returns null for widgets that need the procedural switch below (complex branching).
  const specsDir = resolveApiSpecs();
  if (specsDir) {
    const catalog = loadWidgetCatalog(specsDir);
    const catalogSteps = catalogDrivenSteps(fieldPath, meta, catalog, label, param, isName, hasDefault);
    if (catalogSteps !== null) return catalogSteps;
  }

  // Procedural fallback for complex widgets (listbox, configurable, resource-selector,
  // nested-resource-list) until their catalog templates encode the branching logic.
  switch (meta.widget_type) {
    case 'textbox':
    case 'textarea': {
      const step: Step = {
        id: isName ? 'fill-name' : `fill-${param}`,
        action: 'fill',
        selector: `textbox[name='${label}']`,
        value: `{${isName ? 'name' : param}}`,
        description: `Enter ${label}${meta.validation?.pattern ? ` (pattern: ${meta.validation.pattern})` : ''}${meta.validation?.max_length ? `, max ${meta.validation.max_length} chars` : ''}`,
      };
      if (!isName && hasDefault) step.condition = `params.${param} is set`;
      return [step];
    }
    case 'spinbutton': {
      const step: Step = {
        id: `fill-${param}`,
        action: 'fill',
        selector: `spinbutton[name='${label}']`,
        value: `{${param}}`,
        description: `Set ${label}${hasDefault ? ` (default: ${meta.default})` : ''}`,
      };
      if (hasDefault) step.condition = `params.${param} is set`;
      return [step];
    }
    case 'listbox': {
      // A listbox that references another object (resource_type set) must be
      // SCOPED by label — a form can have several listboxes and a bare `listbox`
      // resolves the first one. Verified: app_api_group's "HTTP Load Balancer"
      // listbox selects an existing http-lb only via listbox[name='HTTP Load Balancer'].
      // Enum listboxes (no resource_type, e.g. enforcement_mode) keep bare `listbox`.
      const step: Step = {
        id: `select-${param}`,
        action: 'select',
        selector: meta.resource_type ? `listbox[name='${label}']` : 'listbox',
        context: `${label} section`,
        value: `{${param}}`,
        description: `Select ${label}${meta.resource_type ? ` (references an existing ${meta.resource_type} — dependency)` : meta.options ? ` (${meta.options.join(' | ')})` : ''}`,
      };
      if (hasDefault) step.condition = `params.${param} is set`;
      return [step];
    }
    case 'checkbox': {
      return [
        {
          id: `check-${param}`,
          action: 'check',
          selector: `checkbox[name='${label}']`,
          condition: `params.${param} is set`,
          description: `Toggle ${label}`,
        },
      ];
    }
    case 'table': {
      // Tables ship with one empty row — fill it directly via ngx-datatable.
      // Use size-agnostic input.form-control (matches -sm and -md variants;
      // http-lb Domains is -md, bgp-asn-set AS Numbers is -sm).
      return [
        {
          id: `fill-${param}`,
          action: 'fill',
          selector: 'ngx-datatable input.form-control',
          context: `${label} table`,
          value: `{${param}}`,
          description: `Enter ${label} in the existing table row (no Add Item needed — the table ships one empty row)`,
        },
      ];
    }
    case 'resource-selector': {
      return [
        {
          id: `attach-${param}`,
          action: 'click',
          selector: "button:text('Add Item')",
          context: `${label} section`,
          condition: `params.${param} is set`,
          description: `Attach ${label} (references a ${meta.resource_type ?? 'resource'})`,
          // biome-ignore lint/suspicious/noThenProperty: 'then' is the workflow schema's nested-step key, not a thenable
          then: [
            {
              id: `select-${param}`,
              action: 'select',
              selector: 'listbox',
              context: `${label} selector`,
              value: `{${param}}`,
              description: `Select the ${label}`,
            },
            {
              id: `apply-${param}`,
              action: 'click',
              selector: "button:text('Apply')",
              description: `Confirm ${label} selection`,
            },
          ],
        },
      ];
    }
    case 'nested-resource-list': {
      // nested-resource-list: click Add Item → fill the minimum sub-form field → Apply.
      // If item_types defines the sub-form structure, use the first field.
      // Otherwise, fill the first visible textbox inside the sub-form as a fallback
      // (the most common minimum is one text input — a name, value, or reference).
      const types = meta.item_types ? Object.entries(meta.item_types) : [];
      const defaultType = types[0];
      // Prefer an explicit sub_field_label from the metadata (discovered via the
      // feedback loop, e.g. ip_prefix_set's inner field is "IPv4 Prefix"), then
      // item_types, then a bare textbox fallback.
      const subLabel = meta.sub_field_label;
      // sub_select_label: the nested item's required field is a RESOURCE-SELECTOR
      // (a listbox referencing an existing object), not a free-text input — e.g.
      // protocol_policer's nested item requires selecting an existing Policer.
      // Discovered via the create-form feedback loop ("Field Policer is required").
      const subSelectLabel = meta.sub_select_label;
      const subResourceType = meta.sub_resource_type;
      const innerField = defaultType?.[1].fields?.[0];
      const fillStep = subSelectLabel
        ? {
            id: `select-${param}-ref`,
            action: 'select' as const,
            // Scope to the named listbox — nested sub-forms often have several
            // listboxes (e.g. protocol_policer's drawer has TCP Packet Type + Policer);
            // a bare `listbox` resolves the first one and misses the target.
            selector: `listbox[name='${subSelectLabel}']`,
            context: `${subSelectLabel} selector`,
            value: `{${toParamName(subSelectLabel)}}`,
            description: `Select the ${subSelectLabel} for the ${label} entry (references an existing ${subResourceType ?? 'resource'} — create one first)`,
          }
        : subLabel
          ? {
              id: `fill-${param}-value`,
              action: 'fill' as const,
              selector: `textbox[name='${subLabel}']`,
              value: `{${toParamName(label)}}`,
              description: `Enter ${subLabel} for the ${label} entry`,
            }
          : innerField
            ? {
                id: `fill-${param}-${innerField}`,
                action: 'fill' as const,
                selector: `textbox[name='${innerField.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}']`,
                value: `{${toParamName(label)}}`,
                description: `Enter ${innerField} for the ${label} entry`,
              }
            : {
                id: `fill-${param}-value`,
                action: 'fill' as const,
                selector: 'textbox',
                value: `{${toParamName(label)}}`,
                description: `Fill the first required field in the ${label} sub-form (the agent should provide a value via the '${param}' parameter)`,
              };
      const noApply = meta.no_apply === true;
      const thenSteps: Step[] = [fillStep];
      if (!noApply) {
        thenSteps.push({
          id: `apply-${param}`,
          action: 'click',
          selector: "button:text('Apply')",
          description: `Confirm ${label} entry`,
        });
      }
      return [
        {
          id: `add-${param}`,
          action: 'click',
          selector: "button:text('Add Item')",
          context: `${label} section`,
          description: `Add ${label} entry${defaultType ? ` (default type: ${defaultType[1].label})` : ''}${noApply ? ' (inline row, no Apply)' : ''}`,
          // biome-ignore lint/suspicious/noThenProperty: 'then' is the workflow schema's nested-step key, not a thenable
          then: thenSteps,
        },
      ];
    }
    case 'configurable': {
      // Configurable fields expand a sub-form via a "Configure" control. Verified
      // live: that control is a LINK, not a button — so use text('Configure'),
      // never button:text (which silently no-ops). SECRET fields (meta.secret,
      // e.g. container_registry password) open a sub-form with a Secret Type
      // listbox (defaulted — leave it), a TEXTAREA for the value, and an Apply
      // button. Non-secret configurables fill the first textbox.
      if (!meta.required) return [];
      const steps: Step[] = [
        {
          id: `configure-${param}`,
          action: 'click',
          selector: `text('${meta.configure_action ?? 'Configure'}')`,
          context: `${label} section`,
          description: `Open the ${label} configuration ('Configure' is a link, not a button)`,
        },
        {
          id: `fill-${param}-value`,
          action: 'fill',
          selector: meta.secret ? 'textarea' : 'textbox',
          value: `{${param}}`,
          description: `Enter the ${label} value${meta.secret ? ' (secret textarea)' : ''} via the '${param}' parameter`,
        },
      ];
      if (meta.secret) {
        steps.push({
          id: `apply-${param}`,
          action: 'click',
          selector: "button:text('Apply')",
          description: `Apply the ${label} secret to commit it`,
        });
      }
      return steps;
    }
    // Skip these — optional, not required for minimal create
    case 'key-value-pairs':
    case 'expandable':
    case 'info-text':
    case 'file-upload-button':
    case 'file-import-button':
      return [];
    default:
      return [];
  }
}

// --- Templates (T3-T5) ---
function generateCreate(
  resourceId: string,
  _kind: string,
  ui: UiResource,
  fields: Record<string, FieldMeta>,
  label: string,
): object {
  const prefix = ui.workspace ? workspacePrefix(ui.workspace) : '';
  const route = `${prefix}${ui.route_pattern ?? ''}`;
  const addLabel = ui.add_action?.label ?? `Add ${label}`;

  // Collect required fields, ordered by form_section
  const sections = ui.form_sections ?? [];
  const sectionOrder = sections.map((s) => s.id);
  const requiredFields = Object.entries(fields)
    .filter(([, m]) => m.required === true && !m.disabled)
    .sort((a, b) => {
      const sa = sectionOrder.indexOf(a[1].form_section ?? '');
      const sb = sectionOrder.indexOf(b[1].form_section ?? '');
      return (sa === -1 ? 999 : sa) - (sb === -1 ? 999 : sb);
    });

  // Build params from required + optional defaults
  const params: Record<string, object> = {
    namespace: { required: true, description: 'Target namespace', example: 'demo' },
    name: {
      required: true,
      description: `${label} name (lowercase alphanumeric and hyphens)`,
      example: `example-${resourceId}`,
    },
  };
  for (const [fp, m] of requiredFields) {
    if (fp === 'metadata.name') continue;
    const p = toParamName(m.label ?? fp);
    if (p === 'name' || p === 'namespace') continue;
    const def: Record<string, unknown> = {
      required: m.default === undefined,
      description: m.description ?? m.label ?? fp,
    };
    if (m.default !== undefined) def.default = m.default;
    if (m.options) def.example = m.options[0];
    params[p] = def;
    // A nested-resource-list whose inner field references another object needs a
    // param naming that object (e.g. protocol_policer → a `policer` to select).
    if (m.sub_select_label) {
      const sp = toParamName(m.sub_select_label);
      params[sp] = {
        required: true,
        description: `Name of an existing ${m.sub_resource_type ?? m.sub_select_label} to reference (dependency — create it first)`,
        example: `example-${m.sub_resource_type ?? sp}`,
      };
    }
  }

  // The Name field may use a non-standard label (e.g. "Role Name", "Credential Name")
  const nameField = fields['metadata.name'];

  // Build steps
  const steps: Step[] = [
    {
      id: 'navigate-to-list',
      action: 'navigate',
      url: `${route}`.replace(/\{namespace\}/, '{namespace}'),
      wait_for: `text('${label}')`,
      description: `Navigate to ${label} list page`,
    },
    {
      id: 'click-add-tab',
      action: 'click',
      // text() matches both [role=tab] (standard workspaces) and <a>/<button>
      // (administration/IAM forms that don't use role=tab).
      selector: `text('${addLabel}')`,
      wait_for: nameField ? `textbox[name='${nameField.label ?? 'Name'}']` : "textbox[name='Name']",
      description: `Click ${addLabel} to open the create form`,
    },
  ];

  for (const [fp, m] of requiredFields) {
    steps.push(...fieldToSteps(fp, m, label));
  }

  // Some workspaces (administration, dns-management, shared-configuration) submit
  // via [class*='submit-button'] ("Add Namespace", "Add DNS Load Balancer", …)
  // instead of the standard [class*='save-bt']. A union CSS selector matches
  // EITHER — the resolver picks the first visible match, which is the right one
  // on each form type. Verified: namespace (submit-button) + 50+ resources (save-bt).
  steps.push({
    id: 'save',
    action: 'click',
    selector: "[class*='save-bt'],[class*='submit-button']",
    context: 'footer',
    wait_for: "text('{name}')",
    wait_timeout_ms: 30000,
    description: `Save/submit the form (union selector matches save-bt OR submit-button)`,
  });

  return {
    schema: 'urn:f5xc:console:workflow:v1',
    id: `${resourceId}-create`,
    label: `Create ${label}`,
    resource: resourceId,
    operation: 'create',
    preconditions: ['user_logged_in', 'namespace_selected', 'role_minimum: admin'],
    params,
    steps,
    postconditions: ['resource_list_page_visible', 'resource_name_in_list: {name}'],
    metadata: { ...GENERATED_METADATA },
  };
}

function generateDelete(resourceId: string, ui: UiResource, label: string): object {
  const prefix = ui.workspace ? workspacePrefix(ui.workspace) : '';
  const route = `${prefix}${ui.route_pattern ?? ''}`;
  return {
    schema: 'urn:f5xc:console:workflow:v1',
    id: `${resourceId}-delete`,
    label: `Delete ${label}`,
    resource: resourceId,
    operation: 'delete',
    preconditions: ['user_logged_in', 'namespace_selected', 'role_minimum: admin', 'resource_exists: {name}'],
    params: {
      namespace: { required: true, example: 'demo' },
      name: { required: true, example: `example-${resourceId}` },
    },
    steps: [
      {
        id: 'navigate-to-list',
        action: 'navigate',
        url: route.replace(/\{namespace\}/, '{namespace}'),
        wait_for: `text('${label}')`,
        description: `Navigate to ${label} list page`,
      },
      {
        id: 'scroll-actions-into-view',
        action: 'scroll',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        description: 'Scroll the Actions column into view for the target row',
      },
      {
        id: 'open-row-actions',
        action: 'click',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        wait_for: "option:text('Delete')",
        description: 'Open the row kebab menu',
      },
      {
        id: 'click-delete',
        action: 'click',
        selector: "option:text('Delete')",
        wait_for: "button:text('Delete')",
        description: 'Click Delete option',
      },
      {
        id: 'confirm-delete',
        action: 'click',
        selector: "button:text('Delete')",
        wait_for: `text('${label}')`,
        wait_timeout_ms: 15000,
        description: 'Confirm deletion',
      },
    ],
    postconditions: ['resource_removed_from_list', 'list_page_visible'],
    metadata: { ...GENERATED_METADATA },
  };
}

function generateRead(resourceId: string, ui: UiResource, label: string): object {
  const prefix = ui.workspace ? workspacePrefix(ui.workspace) : '';
  const route = `${prefix}${ui.route_pattern ?? ''}`;
  return {
    schema: 'urn:f5xc:console:workflow:v1',
    id: `${resourceId}-read`,
    label: `Read ${label}`,
    resource: resourceId,
    operation: 'read',
    params: {
      namespace: { required: true, example: 'demo' },
      name: { required: true, example: `example-${resourceId}` },
    },
    steps: [
      {
        id: 'navigate-to-list',
        action: 'navigate',
        url: route.replace(/\{namespace\}/, '{namespace}'),
        wait_for: `text('${label}')`,
        description: `Navigate to ${label} list page`,
      },
      {
        id: 'scroll-actions-into-view',
        action: 'scroll',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        description: 'Scroll the Actions column into view for the target row',
      },
      {
        id: 'open-row-actions',
        action: 'click',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        wait_for: "option:text('Manage Configuration')",
        description: 'Open the row kebab menu',
        note: 'F5 XC rows have no clickable name → detail page; Read opens the config via the kebab',
      },
      {
        id: 'open-configuration',
        action: 'click',
        selector: "option:text('Manage Configuration')",
        wait_for: "button:text('Edit Configuration')",
        wait_timeout_ms: 15000,
        description: 'Open the read-only Manage Configuration view',
        note: "The config opens read-only (Form/JSON tabs); the agent reads field values via get_page_text/javascript_tool. The 'Edit Configuration' button confirms the view loaded.",
      },
    ],
    metadata: { ...GENERATED_METADATA },
  };
}

function generateUpdate(resourceId: string, ui: UiResource, label: string): object {
  const prefix = ui.workspace ? workspacePrefix(ui.workspace) : '';
  const route = `${prefix}${ui.route_pattern ?? ''}`;
  return {
    schema: 'urn:f5xc:console:workflow:v1',
    id: `${resourceId}-update`,
    label: `Update ${label}`,
    resource: resourceId,
    operation: 'update',
    params: {
      namespace: { required: true, example: 'demo' },
      name: { required: true, example: `example-${resourceId}` },
    },
    steps: [
      {
        id: 'navigate-to-list',
        action: 'navigate',
        url: route.replace(/\{namespace\}/, '{namespace}'),
        wait_for: `text('${label}')`,
        description: `Navigate to ${label} list page`,
      },
      {
        id: 'scroll-actions-into-view',
        action: 'scroll',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        description: 'Scroll the Actions column into view',
      },
      {
        id: 'open-row-actions',
        action: 'click',
        selector: "row:has-text('{name}') >> [ves-e2e-test='row-action-dropdown']",
        wait_for: "option:text('Manage Configuration')",
        description: 'Open the row kebab menu',
      },
      {
        id: 'open-configuration',
        action: 'click',
        selector: "option:text('Manage Configuration')",
        wait_for: "button:text('Edit Configuration')",
        wait_timeout_ms: 15000,
        description: 'Open the read-only Manage Configuration view',
      },
      {
        id: 'enter-edit-mode',
        action: 'click',
        // MUST be button-scoped: a bare text('Edit Configuration') resolves the
        // wrapper element and the click is a no-op (verified live).
        selector: "button:text('Edit Configuration')",
        wait_for: "[class*='save-bt'],[class*='submit-button']",
        wait_timeout_ms: 20000,
        description: "Click 'Edit Configuration' to switch from read-only view into the editable form",
      },
      {
        id: 'modify-fields',
        action: 'wait',
        selector: "[class*='save-bt'],[class*='submit-button']",
        description: 'The agent fills the specific fields the user asked to modify (dynamic, not pre-generated)',
      },
      {
        id: 'save',
        action: 'click',
        selector: "[class*='save-bt'],[class*='submit-button']",
        context: 'footer',
        wait_for: `text('${label}')`,
        wait_timeout_ms: 30000,
        description: 'Save/submit changes (union selector matches save-bt OR submit-button)',
      },
    ],
    metadata: { ...GENERATED_METADATA },
  };
}

// --- Main ---
const specsDir = resolveApiSpecs();
if (!specsDir) {
  console.error('api-specs-enriched not found');
  process.exit(1);
}

const fieldMetadata = (
  parseYaml(fs.readFileSync(path.join(specsDir, 'config/console_field_metadata.yaml'), 'utf8')) as any
).resources as Record<string, Record<string, FieldMeta>>;
const uiRaw = parseYaml(fs.readFileSync(path.join(specsDir, 'config/console_ui.yaml'), 'utf8')) as any;
const uiConfig = (uiRaw.resources ?? uiRaw) as Record<string, UiResource>;

// Read existing resource catalog for label + api.kind mapping
const resourcesDir = path.join(CONSOLE_ROOT, 'catalog/resources');
const catalogResources = new Map<string, { kind: string; label: string }>();
for (const f of fs.readdirSync(resourcesDir).filter((f) => f.endsWith('.yaml'))) {
  const id = f.replace('.yaml', '');
  const doc = parseYaml(fs.readFileSync(path.join(resourcesDir, f), 'utf8')) as any;
  catalogResources.set(id, { kind: doc?.api?.kind ?? '', label: doc?.label ?? id });
}

const dryRun = process.argv.includes('--dry-run');
const filterResource = process.argv.includes('--resource')
  ? process.argv[process.argv.indexOf('--resource') + 1]
  : null;
const preserveHandcrafted = !process.argv.includes('--overwrite');

let generated = 0;
let skipped = 0;
let preserved = 0;

for (const [resourceId, { kind, label }] of [...catalogResources.entries()].sort()) {
  if (filterResource && resourceId !== filterResource) continue;
  const ui = uiConfig[kind] ?? {};
  const fields = fieldMetadata[kind] ?? {};
  if (!ui.route_pattern) {
    skipped++;
    continue;
  } // no console route = not navigable

  const dir = path.join(WORKFLOWS_DIR, resourceId);

  if (dryRun) {
    const reqCount = Object.values(fields).filter((m) => m.required).length;
    console.log(
      `${resourceId.padEnd(30)} kind=${kind.padEnd(25)} fields=${Object.keys(fields).length.toString().padEnd(3)} required=${reqCount} route=${ui.route_pattern}`,
    );
    generated++;
    continue;
  }

  fs.mkdirSync(dir, { recursive: true });

  for (const [op, gen] of [
    ['create', () => generateCreate(resourceId, kind, ui, fields, label)],
    ['delete', () => generateDelete(resourceId, ui, label)],
    ['read', () => generateRead(resourceId, ui, label)],
    ['update', () => generateUpdate(resourceId, ui, label)],
  ] as const) {
    const file = path.join(dir, `${op}.yaml`);
    // Preserve hand-crafted workflows (confidence: validated) unless --overwrite
    if (preserveHandcrafted && fs.existsSync(file)) {
      try {
        const existing = parseYaml(fs.readFileSync(file, 'utf8')) as any;
        if (existing?.metadata?.confidence === 'validated') {
          preserved++;
          continue;
        }
      } catch {
        /* corrupt YAML — overwrite */
      }
    }
    const workflow = (gen as () => object)();
    fs.writeFileSync(file, stringifyYaml(workflow, { lineWidth: 120 }));
  }
  generated++;
}

console.log(
  `\n${dryRun ? 'Dry run' : 'Generated'}: ${generated} resources, ${skipped} skipped (no route), ${preserved} hand-crafted preserved`,
);
